# Generated by Django 5.2.4 on 2026-02-09 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_ranking_threshold', models.IntegerField(default=2, help_text='Minimum number of screeners for high conviction')),
            ],
            options={
                'verbose_name_plural': 'Global Settings',
            },
        ),
    ]
