# Generated by Django 5.2.4 on 2026-02-15 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_globalsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file_path', models.CharField(help_text='Path to the CSV report file', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_stocks', models.IntegerField(default=0, help_text='Total number of stocks in this scan')),
                ('high_conviction_count', models.IntegerField(default=0, help_text='Number of high conviction stocks')),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='analyzer.scanjob')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
